-- Generated by ch-pd-service-status.js @ Tue Feb 27 2018 16:49:03 GMT-0800 (Pacific Standard Time)
-- CASA-11034: out-of-sync
-- 1.  Suspend contract_identity: 1000006017, contract_id: 6018 
update gms4.sms_customer_services 
set service_status_id = 1, last_updated = current timestamp 
where contract_id = 6018 AND service_type_id IN ( 1 ); 

update gms4.sms_customer_services 
set service_status_id = 1, last_updated = current timestamp 
where contract_id = 6018 AND service_type_id IN ( 500 ); 
         
update gms4.sms_customer_contacts 
set status = 1, last_updated = current timestamp 
where contract_id = 6018; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6018; 
 
commit;     
-- 3.  Suspend contract_identity: 1000006019, contract_id: 6020 
update gms4.sms_customer_services 
set service_status_id = 3, last_updated = current timestamp 
where contract_id = 6020 AND service_type_id IN ( 1 ); 

update gms4.sms_customer_services 
set service_status_id = 1, last_updated = current timestamp 
where contract_id = 6020 AND service_type_id IN ( 500 ); 
         
update gms4.sms_customer_contacts 
set status = 0, last_updated = current timestamp 
where contract_id = 6020; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6020; 
 
commit;     
-- 5.  Suspend contract_identity: 1000006036, contract_id: 6037 
update gms4.sms_customer_services 
set service_status_id = 3, last_updated = current timestamp 
where contract_id = 6037 AND service_type_id IN ( 1 ); 
         
update gms4.sms_customer_services 
set service_status_id = 1, last_updated = current timestamp 
where contract_id = 6037 AND service_type_id IN ( 500 ); 

update gms4.sms_customer_contacts 
set status = 1, last_updated = current timestamp 
where contract_id = 6037; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6037; 
 
commit;     
-- 6.  Suspend contract_identity: 1000006072, contract_id: 6073 
update gms4.sms_customer_services 
set service_status_id = 1, last_updated = current timestamp 
where contract_id = 6073 AND service_type_id IN ( 1 ); 
         
update gms4.sms_customer_services 
set service_status_id = 3, last_updated = current timestamp 
where contract_id = 6073 AND service_type_id IN ( 500 ); 

         
update gms4.sms_customer_contacts 
set status = 1, last_updated = current timestamp 
where contract_id = 6073; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6073; 
 
commit;     
-- 7.  Suspend contract_identity: 1000006073, contract_id: 6074 
update gms4.sms_customer_services 
set service_status_id = 2, last_updated = current timestamp 
where contract_id = 6074 AND service_type_id IN ( 1 ); 
         
update gms4.sms_customer_services 
set service_status_id = 3, last_updated = current timestamp 
where contract_id = 6074 AND service_type_id IN ( 500 ); 
        
update gms4.sms_customer_contacts 
set status = 1, last_updated = current timestamp 
where contract_id = 6074; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6074; 
 
commit;     
-- 8.  Suspend contract_identity: 1000006074, contract_id: 6075 
update gms4.sms_customer_services 
set service_status_id = 3, last_updated = current timestamp 
where contract_id = 6075 AND service_type_id IN ( 1 ); 
         
update gms4.sms_customer_services 
set service_status_id = 2, last_updated = current timestamp 
where contract_id = 6075 AND service_type_id IN ( 500 ); 
         
update gms4.sms_customer_contacts 
set status = 1, last_updated = current timestamp 
where contract_id = 6075; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6075; 
 
commit;     
-- 10. Suspend contract_identity: 1000006078, contract_id: 6079 
update gms4.sms_customer_services 
set service_status_id = 3, last_updated = current timestamp 
where contract_id = 6079 AND service_type_id IN ( 1 ); 
         
update gms4.sms_customer_services 
set service_status_id = 3, last_updated = current timestamp 
where contract_id = 6079 AND service_type_id IN ( 500 ); 
         
update gms4.sms_customer_contacts 
set status = 1, last_updated = current timestamp 
where contract_id = 6079; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6079; 
 
commit;     
