-- Generated by ch-pd-service-status.js @ Tue Feb 27 2018 16:48:28 GMT-0800 (Pacific Standard Time)
-- CASA-11034: out-of-sync
-- Preactivate(1) contract_identity: 1000006077, contract_id: 6078 
update gms4.sms_customer_services 
set service_status_id = 2, last_updated = current timestamp 
where contract_id = 6078 AND service_type_id IN ( 1, 500 ); 
         
update gms4.sms_customer_contacts 
set status = 0, last_updated = current timestamp 
where contract_id = 6078; 
 
update gms4.sms_contracts 
set last_updated = current timestamp 
where contract_id = 6078; 
 
commit;     
